### ISSUE TITLE
Add recommendation to not loop over hosts but use the inventory

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/automation-good-practices#26]
### Anti-pattern:

```yaml
list_of_hosts_to_create:
  host1: var1, var2, var3
  host2: var1, var2, var3
```

then loop over the list and (often) create the host against oVirt, vSphere, etc...

### Recommended pattern:

```
inventory/host_vars/{host1,host2}/vm_create.yml (with var1, var2, var3 + variable vm_creation_server)
```

then:

```yaml
- hosts: vms_to_be_created
  gather_facts: false  # important or it will fail if the VM doesn't exist yet
  tasks:
    - name: create VM(s)
       create_vm:
          vm_creation_endpoint: "{{ vm_creation_server }}"
          [ ... etc ... ]
```

Rationale: is parallelized automatically by Ansible, easier to maintain, easier to `--limit` to certain hosts
